// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQDiZb--47GtYE9UaN8JAWmhGI7nIeBBM',
    appId: '1:872035218234:web:13ac3c04d2ddb225155603',
    messagingSenderId: '872035218234',
    projectId: 'location-based-file-sharing',
    authDomain: 'location-based-file-sharing.firebaseapp.com',
    storageBucket: 'location-based-file-sharing.appspot.com',
    measurementId: 'G-BW8DWLV2NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7QYwdERQfag5ILoRTDHsGRYP2u411-c',
    appId: '1:872035218234:android:a3a0f293219ea16f155603',
    messagingSenderId: '872035218234',
    projectId: 'location-based-file-sharing',
    storageBucket: 'location-based-file-sharing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZQPjhtdb74EF5HL3EMXadevimNcujqg',
    appId: '1:872035218234:ios:c78fa544d66b9367155603',
    messagingSenderId: '872035218234',
    projectId: 'location-based-file-sharing',
    storageBucket: 'location-based-file-sharing.appspot.com',
    iosClientId: '872035218234-vi24vq5em7g11dbro8nq9bm2rcbl51j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileCosmos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQZQPjhtdb74EF5HL3EMXadevimNcujqg',
    appId: '1:872035218234:ios:c78fa544d66b9367155603',
    messagingSenderId: '872035218234',
    projectId: 'location-based-file-sharing',
    storageBucket: 'location-based-file-sharing.appspot.com',
    iosClientId: '872035218234-vi24vq5em7g11dbro8nq9bm2rcbl51j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileCosmos',
  );
}
